/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package personal.chris.unciv.notifier

import org.junit.jupiter.api.Nested
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class NotifierTest {

    @Nested
    class ValidateArgs {

        @Test fun validatesNoArgs() {
            val validationError = Notifier.validateArgs(emptyArray());

            assertNotNull(validationError)
            assertEquals("Must supply 1 arg (path to watch), received: 0", validationError)
        }

        @Test fun validatesTwoArgs() {
            val validationError = Notifier.validateArgs(arrayOf("arg1", "arg2"));

            assertNotNull(validationError)
            assertEquals("Must supply 1 arg (path to watch), received: 2", validationError)
        }

        @Test fun validatesNonExistentFile() {
            val validationError = Notifier.validateArgs(arrayOf("not-a-file"));

            assertNotNull(validationError)
            assertEquals("File at not-a-file does not exist", validationError)
        }
    }


}
