/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package personal.chris.unciv.notifier

import kotlin.test.Test
import kotlin.test.assertNotNull

class UncivNotifierTest {
    @Test fun appHasAGreeting() {
        val classUnderTest = UncivNotifier()
    }
}
