/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package personal.chris.unciv.notifier

class UncivNotifier {

}

fun main(args: Array<String>) {
    val config = Config.fromArgs(args)
    val notifier = Notifier(config)
    val monitor = Monitor(config, notifier)
    monitor.monitor()
}
