/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package personal.chris.unciv.notifier

class UncivNotifier {

}

fun main(args: Array<String>) {
    val notifier = Notifier()
    val monitor = Monitor(args, notifier)
    monitor.monitor()
}