/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package personal.chris.unciv.notifier

import kotlin.system.exitProcess

class UncivNotifier {

}

fun main(args: Array<String>) {
    if (args.size != 1) {
        println("Must supply 1 arg (path to watch), received: ${args.size}")
        exitProcess(1)
    }
    println("Notification service watching for changes in ${args[0]}")
}